/*
===============================================================================
Project:      AdventureWorks2022 SQL Analysis
File:         03_order_value_analysis.sql
Purpose:      Investigate the composition and product contribution of
              high-value sales orders
Database:     AdventureWorks2022
DBMS:         Microsoft SQL Server
===============================================================================

Analytical Focus:

    1. Examine the composition of high-value sales orders
    2. Investigate the relationship between order lines, quantity,
       unit price, and total order value
    3. Identify products contributing most to high-value orders
    4. Calculate product contribution percentages

Key Measures:

    Order-line value = OrderQty × UnitPrice
    Order value      = SUM(OrderQty × UnitPrice)

Important Analytical Distinction:

    02_relationship_analysis.sql
        Establishes how the core tables relate and demonstrates the
        movement from order-line grain to order grain.

    03_order_value_analysis.sql
        Builds on those relationships to investigate what contributes
        to high order value and how product value is distributed.

===============================================================================
*/

USE AdventureWorks2022;
GO

/*=============================================================================
1. COMPOSITION OF THE 50 HIGHEST-VALUE ORDERS
=============================================================================*/

-- Examine the characteristics of the 50 highest-value orders.
--
-- Total_Order_Items:
--     Number of individual order-detail records.
--
-- Total_Quantity:
--     Total number of units ordered.
--
-- Average_Unit_Price:
--     Average unit price across the order's detail lines.
--
-- Total_Order_Amount:
--     Calculated total value of the order.
--
-- This allows order value to be examined in relation to
-- quantity, number of order lines, and unit price.

SELECT TOP 50
    Sale.SalesOrderID,
    COUNT(Detail.SalesOrderDetailID) AS Total_Order_Items,
    SUM(Detail.OrderQty) AS Total_Quantity,
    AVG(Detail.UnitPrice) AS Average_Unit_Price,
    SUM(Detail.OrderQty * Detail.UnitPrice) AS Total_Order_Amount
FROM Sales.SalesOrderHeader AS Sale
INNER JOIN Sales.SalesOrderDetail AS Detail
    ON Detail.SalesOrderID = Sale.SalesOrderID
GROUP BY
    Sale.SalesOrderID
ORDER BY
    Total_Order_Amount DESC;


/*=============================================================================
2. PRODUCTS WITHIN THE 50 HIGHEST-VALUE ORDERS
=============================================================================*/

-- Identify the products contained within the 50 highest-value orders.
--
-- The subquery first identifies the relevant SalesOrderIDs.
-- The outer query then returns the individual order-line records
-- associated with those selected orders.

SELECT TOP 50
    Detail.SalesOrderID,
    Detail.ProductID,
    Detail.OrderQty,
    Detail.UnitPrice,
    Prod.Name
FROM Sales.SalesOrderDetail AS Detail
INNER JOIN Production.Product AS Prod
    ON Prod.ProductID = Detail.ProductID
WHERE Detail.SalesOrderID IN
(
    SELECT TOP 50
        SalesOrderID
    FROM Sales.SalesOrderDetail
    GROUP BY
        SalesOrderID
    ORDER BY
        SUM(OrderQty * UnitPrice) DESC
)
ORDER BY
    Detail.SalesOrderID,
    Detail.ProductID;


/*=============================================================================
3. TOP PRODUCTS BY VALUE WITHIN THE 10 HIGHEST-VALUE ORDERS
=============================================================================*/

-- Identify the products generating the greatest sales value
-- across the 10 highest-value sales orders.
--
-- The outer query changes the grain from order-line level
-- to product level by grouping on ProductID and Product Name.

SELECT TOP 10
    Detail.ProductID,
    Prod.Name,
    SUM(Detail.OrderQty) AS Total_Quantity,
    SUM(Detail.UnitPrice * Detail.OrderQty) AS Total_Product_Value
FROM Sales.SalesOrderDetail AS Detail
INNER JOIN Production.Product AS Prod
    ON Prod.ProductID = Detail.ProductID
WHERE Detail.SalesOrderID IN
(
    SELECT TOP 10
        SalesOrderID
    FROM Sales.SalesOrderDetail
    GROUP BY
        SalesOrderID
    ORDER BY
        SUM(OrderQty * UnitPrice) DESC
)
GROUP BY
    Detail.ProductID,
    Prod.Name
ORDER BY
    Total_Product_Value DESC;


/*=============================================================================
4. PRODUCT CONTRIBUTION TO HIGH-VALUE ORDER REVENUE
=============================================================================*/

-- Calculate the percentage contribution of each product to the
-- total product value generated within the 10 highest-value orders.
--
-- Inner SUM:
--     Calculates the total value generated by each product.
--
-- Window SUM:
--     Calculates the total value across ALL grouped products
--     within the selected high-value orders.
--
-- Product contribution:
--
--     Product Value / Total Value × 100
--
-- IMPORTANT:
--     TOP 10 limits the displayed products AFTER product aggregation.
--     Therefore, Product_Contribution_Percentage represents each
--     displayed product's contribution to the total value across
--     ALL products in the selected high-value orders.
--
--     The percentages displayed will NOT necessarily sum to 100%.

SELECT TOP 10
    Detail.ProductID,
    Prod.Name,
    SUM(Detail.OrderQty) AS Total_Quantity,
    SUM(Detail.UnitPrice * Detail.OrderQty) AS Total_Product_Value,

    SUM(Detail.UnitPrice * Detail.OrderQty)
        / SUM(SUM(Detail.UnitPrice * Detail.OrderQty)) OVER () * 100
        AS Product_Contribution_Percentage

FROM Sales.SalesOrderDetail AS Detail

INNER JOIN Production.Product AS Prod
    ON Prod.ProductID = Detail.ProductID

WHERE Detail.SalesOrderID IN
(
    SELECT TOP 10
        SalesOrderID
    FROM Sales.SalesOrderDetail
    GROUP BY
        SalesOrderID
    ORDER BY
        SUM(OrderQty * UnitPrice) DESC
)

GROUP BY
    Detail.ProductID,
    Prod.Name

ORDER BY
    Total_Product_Value DESC;


/*=============================================================================
5. ANALYTICAL OBSERVATIONS
=============================================================================

High-value order analysis established the following:

1. High order value can result from different combinations of quantity
   and unit price.

2. A greater number of units does not necessarily result in the
   highest-value order.

3. The number of order lines provides additional context for understanding
   how an order is constructed.

4. Unit price materially affects total order value alongside quantity.

5. Products with high quantities do not necessarily generate the highest
   sales value.

6. Product sales value within high-value orders is distributed across
   multiple products rather than being concentrated in a single product.

7. Product contribution percentages provide a relative measure of how
   individual products contribute to the value generated by the selected
   high-value orders.

8. The contribution percentages displayed in Query 4 represent the
   contribution of the TOP 10 displayed products relative to ALL products
   contained within the selected high-value orders. Therefore, their
   percentages should not be expected to total 100%.

===============================================================================
*/
